name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Enables manual trigger

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated to v3
        with:
          node-version: '16'  # You can update to node-version: '20' when needed

      - name: Install dependencies
        run: npm install

      - name: Build Electron App for macOS
        run: npm run build:mac

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MacOS Build
          path: dist/
